<section class="contenido-pagina">
	<div class="contenido-interno">
    	<!-- SUBMENU PAG INTERNAS -->
        <div class="submenu-interno">
        	<h1>Nosotros</h1>
            <ul>
            		<li class="selected-opc">HISTORIA</li>
                        <li><a href="<?php echo $this->createUrl('site/page',array('view'=>'mission')) ?>">MISIÓN Y VISIÓN</a></li>
                        <li ><a href="<?php echo $this->createUrl('site/page',array('view'=>'crifas')) ?>">HOSPITAL EN CIFRAS</a></li>
                        <li ><a href="<?php echo $this->createUrl('site/page',array('view'=>'conventions')) ?>">CONVENIOS</a></li>
                        <li><a href="<?php echo $this->createUrl('site/page',array('view'=>'rights')) ?>">DERECHOS Y OBLIGACIONES</a></li>
                        <li><a href="<?php echo $this->createUrl('site/Authorities',array()) ?>">AUTORIDADES</a></li>
            </ul>
        </div>
        <!-- -->
        <div class="contenido-pag-internas">
        	<h1>Historia</h1>
            <img src="<?php echo Yii::app()->request->getBaseUrl(true); ?>/images/img-hospital.jpg" alt="imagen hospital"/>
            <span>
            En 1977 un grupo de prestigiosos médicos visionarios gestó con gran optimismo la idea de construir, en la ciudad de Quito, un centro hospitalario con estándares internacionales. Dos años más tarde, en 1979, en una alianza estratégica e histórica con la compañía norteamericana AMI, American Medical International, se constituye Conclina C.A. que nos conduciría a dar inicio a un proyecto médico hospitalario que transformaría la atención médica en el país.<br/><br/>
En 1982 empieza la construcción del hospital y tres años más tarde, el 14 de noviembre de 1985, el Hospital Metropolitano abrió sus puertas a la comunidad, iniciando una nueva era en la medicina en el país, creando un nuevo modelo de gestión hospitalaria, al tiempo que se erigía en un dinámico polo de desarrollo de la ciudad.<br/><br/>
Desde sus comienzos, el hospital demostró sensibilidad social, y es así que en 1986 nace la Fundación Metrofraternidad, la más clara expresión de solidaridad, que con el invalorable apoyo del Cuerpo Médico del Hospital, brinda asistencia médica sin costo a miles de pacientes de escasos recursos.<br/><br/>
La historia del hospital ha sido de constante crecimiento e innovación:
En 1990 el hospital amplió su área de atención de consulta externa con el Edificio Diagnóstico 2000 y el Centro Médico Metropolitano.<br/><br/>
El hospital he estado siempre a la vanguardia del conocimiento, en 1992 el Metropolitano se convirtió en hospital docente, modelo de educación con auspicio universitario, llegando a ser un referente de formación profesional en el ámbito de postgrado, contribuyendo así al desarrollo de la salud en el Ecuador.<br/><br/>
En 1995 el hospital implementó el servicio de Resonancia Magnética Nuclear.<br/><br/>
Desarrolló los conocimientos, las destrezas y la tecnología necesaria para atender programas especiales de cirugía laparoscópica, de corazón abierto, trasplantes y otros procedimientos de alta complejidad.<br/><br/>
En el 2001 se inició la actualización tecnológica con la adquisición de un Angiógrafo Digital de última generación.<br/><br/>
En 2002 empezó la renovación de la imagen del hospital iniciando un nuevo proceso de actualización tecnológica y la remodelación de su infraestructura, para volverla aún más amigable y cercana a nuestros pacientes y visitantes.<br/><br/>
El 2003 fue un año muy importante.<br/> <br/>Decenas de personas encontraron por fin una alternativa para garantizar su vida. El Hospital Metropolitano se convirtió en el primer centro acreditado en el país para realizar trasplante renal con donante cadavérico. Un proceso que se desarrolla con mucho éxito y bajo estrictos parámetros éticos.<br/><br/>
En el 2004 pone a disposición de los pacientes el Quirófano Inteligente OR1 primero y único en el país y el más avanzado en Latinoamérica.<br/><br/>
En el 2005 adquiere un equipo de resonancia magnética 1,5 Tesla, y continúa en sus procesos de remodelación.
<br/>En 2006, la institución implementa el Sistema Integral de la Calidad (SGIC) para garantizar la más alta calidad en los servicios que presta a sus usuarios; se implementa, también el navegador "Orthopilot", equipo de alta tecnología para implantar prótesis con gran exactitud.<br/><br/>
En el 2007 abre las puertas de Metrolaser, el centro de láser más moderno del país para corregir la visión.<br/><br/>En abril de 2007, el hospital es certificado con la ISO 9001:2000; a finales de 2007 se adquiere un tomógrafo multicorte 64 de última generación, así como un neuroendoscopio y aspirador ultrasónico y el sistema de ecografía volumétrica de 4 dimensiones, el más rápido del mundo. En el 2008 se adquiere lo último en tecnología láser para tratamientos dermatológicos y estéticos, se trata del recién llegado a Ecuador Equipo Láser marca Fotona. Siguiendo la misma línea de tratamientos con láser, el hospital obtiene una nueva tecnología para intervenciones de próstata llamado Green Light, ésta nueva dimensión de tratamiento es menos invasiva y no requiere de hospitalización.<br/><br/>
El año 2009 se ha constituido como un periodo de reactivación de los programas de trasplante en diferentes áreas. Se convierte en la institución con el mayor número de trasplantes renales en el país. Se realiza un importante convenio entre el Ministerio de Salud Pública, el Ministerio de Inclusión Económica y Social y el Hospital Metropolitano para realizar, por primer vez en el país, trasplantes hepáticos, convirtiéndose en el único centro de salud calificado para realizar este tipo de cirugías. El Hospital Metropolitano, siempre a la vanguardia en tecnología, adquiere nuevos equipos y procedimientos pioneros en el país, es el caso de la Cápsula Endoscópica y el sistema Ris & Pacs. La Cápsula Endoscópica es un procedimiento que explora y evalúa el intestino delgado, colon y esófago por medio de una cámara que se encuentra dentro de una pequeña cápsula, siendo la opción más efectiva en el mercado. El sistema Ris & Pacs es un nuevo servicio que ofrece el área de radiología que consiste en integrar imágenes digitales con sus reportes e información global del paciente poniéndolas a disposición tanto del radiólogo como del resto de médicos del hospital.<br/><br/>
Entrando en el año de su vigésimo séptimo aniversario, el Hospital Metropolitano sigue fiel a su compromiso de servicio e innovación, es así que dentro de su plan de expansión, el Hospital Metropolitano inauguró en marzo del 2010 la Torre Médica 1, primera edificación terminada de las 3 en proyecto. Estas edificaciones albergarán consultorios médicos, cafetería, farmacia, agencia bancaria, y locales comerciales afines, aportará con plazas de parqueo y contribuirá al ornato de la ciudad, por su moderno y generoso diseño.<br/><br/>
Continuando en el proceso de expansión, el hospital abre las puertas de su moderna Unidad de Radioterapia, como parte del Centro Integral de Cáncer "Metrovida", para brindar el servicio de la más alta calidad en el tratamiento del cáncer. La Unidad cuenta con los estándares requeridos y un equipo de la más alta tecnología llamado Acelerador Lineal, el cual es capaz de producir fotones con mega voltaje que concentra la dosis de radiación en el tejido enfermo y protege al tejido sano.<br/><br/>
El Hospital Metropolitano fue nuevamente certificado con la ISO 9001:2008 por el cumplimiento de requisitos en los productos y servicios que ofrece a la comunidad. Este tendrá vigencia hasta el 2010. Además, en el 2009, Conclina C.A  Hospital Metropolitano obtuvo la calificación de riesgo AAA- por parte de la firma BankWatch Rattings, siendo la más alta calificación que se confiere en el Ecuador, lo que le ha permitido tranzar exitosamente sus acciones en las distintas bolsas de valores.<br/><br/>
El 18 de noviembre del 2010, recibió un reconocimiento especial por parte de Great Place to Work, empresa que mide el ambiente laboral y las prácticas de gestión de personas, por ser la empresa que registró el mayor mejoramiento en su ambiente laboral. En este mismo mes, la revista América Economía calificó al Hospital Metropolitano como el número 1 en Ecuador y 26 en Latinoamérica en el sector Salud, en el que existen más de 20.000 centros hospitalarios entre públicos y privados.<br/><br/>
El 14 de noviembre del 2010, el Hospital Metropolitano cumplió 28 años en el mercado de la salud siguiendo con su brillante trayectoria al brindar excelencia en sus servicios y calidad en su atención. El Hospital Metropolitano, en sus primeros 28 años en el mercado de la salud,continuará con su brillante trayectoria al brindar excelencia en sus servicios, seguridad al paciente y calidad en su atención.<br/><br/>
En diciembre del 2010, el Hospital Metropolitano adquirió un equipo de última generación en Resonancia Magnética 3 tesla, misma que tiene mayor potencia admitido para el estudio morfológico del cuerpo humano, siendo el primer equipo en Ecuador con estas características.
            </span>
        </div>
        <!-- -->
    </div>
</section>